// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/page2": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/page2";
  };
  "../routes/home.tsx": {
    id: "../routes/home";
    page: "/";
  };
  "../routes/page2.tsx": {
    id: "../routes/page2";
    page: "/page2";
  };
};